services:
  nginx:
    image: nginx:1.19.2-alpine
    hostname: nginx
    volumes:
      - ${PWD}/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "15000:15000"
    networks:
      - nebula-net
    extra_hosts:
      - "host.docker.internal:host-gateway"
